package net.exmo.exworld.client.monster;

import com.google.gson.GsonBuilder;
import net.exmo.exworld.monster.*;
import net.exmo.exworld.network.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.*;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.neoforged.neoforge.network.PacketDistributor;
import java.util.*;

/** Functional template/rule editor. The server remains the authority for IDs, ranges and skills. */
public final class MonsterEditorScreen extends Screen {
    private static MonsterEditorPayload latest; private final List<MonsterTemplate> templates=new ArrayList<>();private final List<MonsterRule> rules=new ArrayList<>();private int selected;
    private EditBox display,maxHealth,health,maxMana,mana,manaPerPhase,initiative,movement,actions,initialHand,draw,skills;private EditBox ruleJson;
    private MonsterEditorScreen(){super(Component.literal("怪物模板编辑器"));}
    public static void install(MonsterEditorPayload payload){latest=payload;Minecraft.getInstance().setScreen(new MonsterEditorScreen());}
    @Override protected void init(){if(latest==null)return;var gson=new GsonBuilder().create();try{templates.clear();templates.addAll(Arrays.asList(gson.fromJson(latest.templatesJson(),MonsterTemplate[].class)));rules.clear();rules.addAll(Arrays.asList(gson.fromJson(latest.rulesJson(),MonsterRule[].class)));}catch(Exception ignored){}if(templates.isEmpty())templates.add(new MonsterTemplate("exworld:monster",MonsterProfilePatch.empty()));selected=Math.max(0,Math.min(selected,templates.size()-1));int x=230,y=38;display=box("显示名称",x,y,170);maxHealth=box("最大生命",x,y+24,80);health=box("当前生命",x+88,y+24,80);maxMana=box("最大法力",x,y+48,80);mana=box("当前法力",x+88,y+48,80);manaPerPhase=box("每阶段法力",x,y+72,80);initiative=box("先攻",x+88,y+72,80);movement=box("移动力",x,y+96,80);actions=box("行动值",x+88,y+96,80);initialHand=box("初始抽牌",x,y+120,80);draw=box("阶段抽牌",x+88,y+120,80);skills=box("技能：id@星级，用逗号分隔",x,y+144,170);ruleJson=box("规则 JSON（高级）",x,y+168,170);ruleJson.setMaxLength(32000);for(int i=0;i<templates.size();i++){final int index=i;addRenderableWidget(Button.builder(Component.literal(templates.get(i).id()),b->{collect();selected=index;loadTemplate();}).bounds(24,48+i*20,190,18).build());}loadTemplate();if(!rules.isEmpty())ruleJson.setValue(gson.toJson(rules));
        addRenderableWidget(Button.builder(Component.literal("新建模板"),b->{collect();templates.add(new MonsterTemplate("exworld:new_template_"+templates.size(),MonsterProfilePatch.empty()));selected=templates.size()-1;clearWidgets();init();}).bounds(24,height-32,75,20).build());addRenderableWidget(Button.builder(Component.literal("复制"),b->{collect();var source=templates.get(selected);templates.add(new MonsterTemplate("exworld:copy_"+templates.size(),source.profile()));selected=templates.size()-1;clearWidgets();init();}).bounds(105,height-32,45,20).build());addRenderableWidget(Button.builder(Component.literal("删除"),b->{if(templates.size()>1){templates.remove(selected);selected=Math.max(0,Math.min(selected,templates.size()-1));clearWidgets();init();}}).bounds(156,height-32,45,20).build());addRenderableWidget(Button.builder(Component.literal("新建规则"),b->{ruleJson.setValue("[{\"id\":\"exworld:new_rule\",\"entity_type\":\"minecraft:zombie\",\"priority\":0}]");}).bounds(230,height-32,75,20).build());addRenderableWidget(Button.builder(Component.literal("保存 ZIP"),b->save()).bounds(310,height-32,75,20).build());addRenderableWidget(Button.builder(Component.literal("返回"),b->{MonsterPackageScreen.open();}).bounds(width-70,height-32,50,20).build());}
    private EditBox box(String hint,int x,int y,int width){EditBox box=new EditBox(font,x,y,width,20,Component.literal(hint));box.setHint(Component.literal(hint));addRenderableWidget(box);return box;}
    private void loadTemplate(){if(templates.isEmpty())return;var p=templates.get(selected).profile();display.setValue(nvl(p.displayName()));maxHealth.setValue(nvl(p.maxHealth()));health.setValue(nvl(p.health()));maxMana.setValue(nvl(p.maxMana()));mana.setValue(nvl(p.mana()));manaPerPhase.setValue(nvl(p.manaPerPhase()));initiative.setValue(nvl(p.initiative()));movement.setValue(nvl(p.movementPoints()));actions.setValue(nvl(p.actionPoints()));initialHand.setValue(nvl(p.initialHandSize()));draw.setValue(nvl(p.drawPerPhase()));skills.setValue(p.skills()==null?"":p.skills().stream().map(s->s.id()+"@"+s.star()).reduce((a,b)->a+", "+b).orElse(""));}
    private void collect(){var old=templates.get(selected);var p=new MonsterProfilePatch(blank(display.getValue()),number(maxHealth),number(health),number(maxMana),number(mana),number(manaPerPhase),decimal(initiative),integer(movement),integer(actions),integer(initialHand),integer(draw),parseSkills(skills.getValue()));templates.set(selected,new MonsterTemplate(old.id(),p));if(ruleJson!=null&&!ruleJson.getValue().isBlank())try{var parsed=new GsonBuilder().create().fromJson(ruleJson.getValue(),MonsterRule[].class);rules.clear();if(parsed!=null)rules.addAll(Arrays.asList(parsed));}catch(Exception ignored){}}
    private void save(){collect();var gson=new GsonBuilder().setPrettyPrinting().create();PacketDistributor.sendToServer(new MonsterPackageActionPayload(MonsterPackageActionPayload.Action.SAVE,latest.packageId(),0,"",gson.toJson(templates),gson.toJson(rules)));}
    private static String nvl(Object v){return v==null?"":String.valueOf(v);}private static String blank(String s){return s.isBlank()?null:s;}private static Float number(EditBox b){try{return b.getValue().isBlank()?null:Float.parseFloat(b.getValue());}catch(Exception e){return null;}}private static Double decimal(EditBox b){try{return b.getValue().isBlank()?null:Double.parseDouble(b.getValue());}catch(Exception e){return null;}}private static Integer integer(EditBox b){try{return b.getValue().isBlank()?null:Integer.parseInt(b.getValue());}catch(Exception e){return null;}}
    private static List<MonsterProfilePatch.Skill> parseSkills(String text){if(text.isBlank())return null;List<MonsterProfilePatch.Skill> result=new ArrayList<>();for(String part:text.split(",")){String[] bits=part.trim().split("@",2);if(bits.length>0&&!bits[0].isBlank())try{result.add(new MonsterProfilePatch.Skill(bits[0].trim(),bits.length>1?Integer.parseInt(bits[1]):1));}catch(Exception ignored){}}return result;}
    @Override public void render(GuiGraphics g,int mx,int my,float pt){renderBackground(g,mx,my,pt);g.drawString(font,title,24,18,0xFFFFFFFF);g.drawString(font,"数据包："+(latest==null?"":latest.displayName()),24,30,0xFFB8C3D1);g.drawString(font,"模板列表（点击切换）",24,38,0xFFFFD98A);int y=48;for(int i=0;i<templates.size();i++){g.drawString(font,(i==selected?"> ":"  ")+templates.get(i).id(),24,y, i==selected?0xFFFFD98A:0xFFE6EAF0);y+=18;}g.drawString(font,"规则 JSON 可一次编辑全部规则；保存前会由服务器校验。",230,214,0xFFB8C3D1);super.render(g,mx,my,pt);}
}
