package net.exmo.exworld.network;

import java.time.Instant;
import java.util.*;
import net.exmo.exworld.Exworld;
import net.exmo.exworld.progress.*;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;

/** One compact server-to-client state transfer for opening/updating the journal. */
public record QuestJournalPayload(QuestJournalSnapshot snapshot) implements CustomPacketPayload {
    public static final Type<QuestJournalPayload> TYPE = new Type<>(ResourceLocation.fromNamespaceAndPath(Exworld.MODID,"quest_journal"));
    public static final StreamCodec<RegistryFriendlyByteBuf,QuestJournalPayload> STREAM_CODEC=StreamCodec.of(QuestJournalPayload::encode,QuestJournalPayload::decode);
    private static void encode(RegistryFriendlyByteBuf b, QuestJournalPayload payload) { QuestJournalSnapshot s=payload.snapshot; b.writeVarInt(s.quests().size()); for(QuestSnapshot q:s.quests()){b.writeUtf(q.id().toString());b.writeEnum(q.kind());b.writeEnum(q.status());b.writeUtf(q.titleKey());b.writeUtf(q.descriptionKey());b.writeUtf(q.nodeId());b.writeUtf(q.nodeTitleKey());b.writeUtf(q.nodeDescriptionKey());b.writeVarInt(q.objectives().size());for(var o:q.objectives()){b.writeEnum(o.type());b.writeUtf(o.target());b.writeVarInt(o.current());b.writeVarInt(o.required());b.writeUtf(o.dimension());b.writeDouble(o.x());b.writeDouble(o.y());b.writeDouble(o.z());}b.writeVarInt(q.branches().size());q.branches().forEach(b::writeUtf);b.writeBoolean(q.navigationTarget()!=null);if(q.navigationTarget()!=null)b.writeUtf(q.navigationTarget().toString());}b.writeVarInt(s.timeline().size());for(var t:s.timeline()){b.writeLong(t.at().toEpochMilli());b.writeLong(t.gameTime());b.writeUtf(t.questId().toString());b.writeUtf(t.type());b.writeUtf(t.detail());}b.writeVarInt(s.mail().size());for(var m:s.mail()){b.writeUUID(m.id());b.writeUtf(m.source());b.writeUtf(m.subject());b.writeLong(m.deliveredAt());b.writeBoolean(m.read());b.writeVarInt(m.attachments().size());m.attachments().forEach(stack->ItemStack.STREAM_CODEC.encode(b,stack));}b.writeVarInt(s.resources().size());s.resources().forEach((id,amount)->{b.writeUtf(id.toString());b.writeLong(amount);});b.writeBoolean(s.pinnedQuest()!=null);if(s.pinnedQuest()!=null)b.writeUtf(s.pinnedQuest().toString()); }
    private static QuestJournalPayload decode(RegistryFriendlyByteBuf b) { List<QuestSnapshot> quests=new ArrayList<>();for(int i=0,n=b.readVarInt();i<n;i++){ResourceLocation id=ResourceLocation.parse(b.readUtf());QuestKind kind=b.readEnum(QuestKind.class);QuestStatus status=b.readEnum(QuestStatus.class);String title=b.readUtf(),desc=b.readUtf(),node=b.readUtf(),nodeTitle=b.readUtf(),nodeDesc=b.readUtf();List<QuestSnapshot.Objective> objectives=new ArrayList<>();for(int j=0,c=b.readVarInt();j<c;j++)objectives.add(new QuestSnapshot.Objective(b.readEnum(QuestObjective.Type.class),b.readUtf(),b.readVarInt(),b.readVarInt(),b.readUtf(),b.readDouble(),b.readDouble(),b.readDouble()));List<String> branches=new ArrayList<>();for(int j=0,c=b.readVarInt();j<c;j++)branches.add(b.readUtf());ResourceLocation nav=b.readBoolean()?ResourceLocation.parse(b.readUtf()):null;quests.add(new QuestSnapshot(id,kind,status,title,desc,node,nodeTitle,nodeDesc,objectives,branches,nav));}List<QuestTimelineEntry> timeline=new ArrayList<>();for(int i=0,n=b.readVarInt();i<n;i++)timeline.add(new QuestTimelineEntry(Instant.ofEpochMilli(b.readLong()),b.readLong(),ResourceLocation.parse(b.readUtf()),b.readUtf(),b.readUtf()));List<QuestJournalSnapshot.Mail> mail=new ArrayList<>();for(int i=0,n=b.readVarInt();i<n;i++){UUID id=b.readUUID();String source=b.readUtf(),subject=b.readUtf();long at=b.readLong();boolean read=b.readBoolean();List<ItemStack> attachments=new ArrayList<>();for(int j=0,c=b.readVarInt();j<c;j++)attachments.add(ItemStack.STREAM_CODEC.decode(b));mail.add(new QuestJournalSnapshot.Mail(id,source,subject,at,read,attachments));}Map<ResourceLocation,Long> resources=new LinkedHashMap<>();for(int i=0,n=b.readVarInt();i<n;i++)resources.put(ResourceLocation.parse(b.readUtf()),b.readLong());ResourceLocation pinned=b.readBoolean()?ResourceLocation.parse(b.readUtf()):null;return new QuestJournalPayload(new QuestJournalSnapshot(quests,timeline,mail,resources,pinned)); }
    @Override public Type<? extends CustomPacketPayload> type(){return TYPE;}
}
